config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :users
  resources :exams do 
    get 'open', to: 'exams#open', as: 'exam_open'
    get 'result', to: 'exams#result', as: 'exam_result'
    post 'eval', to: 'exams#eval', as: 'exam_eval'
    resources :questions do 
      resources :options
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :exam
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exam.rb
class Exam < ApplicationRecord
    has_many :questions
    has_many :answers
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :exam
  has_many :options, dependent: :delete_all
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :answers

  def exam_state(exam_id)
    Answer.where(user: self).where(exam: Exam.find(exam_id)).count > 0
  end

  def answer_checked(exam_id, option_id)
    answers = Answer.where(user: self).where(exam: Exam.find(exam_id)).first
    arr = answers.answers.split(", ")    
    
    arr.include? option_id.to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :set_exam, only: [:show, :edit, :update, :destroy]

  # GET /exams
  # GET /exams.json
  def index
    @exams = Exam.all
  end

  def open
    @exam = Exam.find(params[:exam_id])
  end

  def result
    @exam = Exam.find(params[:exam_id])
  end 

  def eval
    answers = JSON.parse(params[:options_question].to_json)
    answers_arr = answers.map{ |a| a[0] }.join(', ')

    @answer = Answer.new
      @answer.user = current_user
      @answer.exam = Exam.find(params[:exam_id])
      @answer.answers = answers_arr
    @answer.save
    redirect_to root_path, notice: 'Examen rendido exitosamente!'
  end

  # GET /exams/1
  # GET /exams/1.json
  def show
    @question = Question.new
  end

  # GET /exams/new
  def new
    @exam = Exam.new
  end

  # GET /exams/1/edit
  def edit
  end

  # POST /exams
  # POST /exams.json
  def create
    @exam = Exam.new(exam_params)

    respond_to do |format|
      if @exam.save
        format.html { redirect_to @exam, notice: 'Exam was successfully created.' }
        format.json { render :show, status: :created, location: @exam }
      else
        format.html { render :new }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exams/1
  # PATCH/PUT /exams/1.json
  def update
    respond_to do |format|
      if @exam.update(exam_params)
        format.html { redirect_to @exam, notice: 'Exam was successfully updated.' }
        format.json { render :show, status: :ok, location: @exam }
      else
        format.html { render :edit }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exams/1
  # DELETE /exams/1.json
  def destroy
    @exam.destroy
    respond_to do |format|
      format.html { redirect_to exams_url, notice: 'Exam was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exam
      @exam = Exam.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def exam_params
      params.require(:exam).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @exams = Exam.all
  end
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  before_action :set_option, only: [:show, :edit, :update, :destroy]
  before_action :set_question, only: [:index, :new, :create, :edit]

  # GET /options
  # GET /options.json
  def index
    @options = Option.where(question_id: params[:question_id]).order("position")
  end

  # GET /options/1
  # GET /options/1.json
  def show
  end

  # GET /options/new
  def new
    @option = Option.new
  end

  # GET /options/1/edit
  def edit
  end

  # POST /options
  # POST /options.json
  def create
    @option = Option.new(option_params)
    @option.question = @question

    respond_to do |format|
      if @option.save
        format.html { redirect_to exam_question_options_path(@question.exam, @question), notice: 'Option was successfully created.' }
        format.json { render :show, status: :created, location: @option }
      else
        format.html { render :new }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /options/1
  # PATCH/PUT /options/1.json
  def update
    respond_to do |format|
      if @option.update(option_params)
        format.html { redirect_to exam_question_options_path(@option.question.exam, @option.question), notice: 'Option was successfully updated.' }
        format.json { render :show, status: :ok, location: @option }
      else
        format.html { render :edit }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /options/1
  # DELETE /options/1.json
  def destroy
    @question = @option.question
    @option.destroy
    respond_to do |format|
      format.html { redirect_to exam_question_options_path(@question.exam, @question), notice: 'Option was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_option
      @option = Option.find(params[:id])
    end

    def set_question
      @question = Question.find(params[:question_id])
    end

    # Only allow a list of trusted parameters through.
    def option_params
      params.require(:option).permit(:content, :position, :is_correct, :question_id)
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :set_exam, only: [:create, :new, :edit, :update]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    @question.exam = @exam

    respond_to do |format|
      if @question.save
        format.html { redirect_to @exam, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @exam, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @exam = @question.exam
    @question.destroy
    respond_to do |format|
      format.html { redirect_to @exam, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    def set_exam
      @exam = Exam.find(params[:exam_id])
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:question).permit(:content, :position)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/exams/_exam.html.erb
<div class="mb-3 p-3 shadow">
    <% if user_signed_in? %>
        <% if current_user.exam_state(exam.id) %>
            <%= link_to 'Ver Resultados', exam_exam_result_path(exam), :class => "btn btn-success float-right" %>
        <% else %>
            <%= link_to 'Ver Exámen', exam_exam_open_path(exam), :class => "btn btn-primary float-right" %>
        <% end %>
    <% else %>
        <i class="float-right">Debes estar autenticado para rendir los examenes</i>
    <% end %>
    <h5 class="mx-2"><i class="fa fa-file-alt" aria-hidden="true"></i> <%= exam.name %></h5>
</div>

app/views/exams/_form.html.erb
<%= form_with(model: exam, local: true) do |form| %>
  <% if exam.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(exam.errors.count, "error") %> prohibited this exam from being saved:</h2>

      <ul>
        <% exam.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label "Nombre Examen" %>
    <%= form.text_field :name, :class => "form-control" %>
  </div>

  <div class="form-group text-right mt-4">
    <%= link_to 'Volver', exams_path, :class => "float-left btn btn-secondary" %>
    <%= form.submit 'Guardar', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/exams/edit.html.erb
<p id="notice"><%= notice %></p>

<div class="p-3 shadow">
    <h3>Editar Examen</h3>
    <%= render 'form', exam: @exam %>
</div>

app/views/exams/index.html.erb
<p id="notice"><%= notice %></p>


<div class="shadow p-3">
  <%= link_to 'Nuevo Exámen', new_exam_path, :class => "float-right btn btn-primary mb-2" %>
  <h3>Examenes</h3>
</div>
<br/>

<div class="shadow p-3">
<table class="table table-bordered">
  <thead class="bg-dark text-white">
    <tr>
      <th>Nombre</th>
      <th>Preguntas</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @exams.each do |exam| %>
      <tr>
        <td><%= exam.name %></td>
        <td><%= exam.questions.count %></td>
        <td class="text-right">
          <%= link_to 'Ver Detalle', exam %>
          <%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_exam_path(exam) %>
          <%= link_to '<i class="fa fa-trash"></i>'.html_safe, exam, :class=>"text-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/exams/new.html.erb
<p id="notice"><%= notice %></p>

<div class="p-3 shadow">
    <h3>Nuevo Examen</h3>
    <%= render 'form', exam: @exam %>
</div>

app/views/exams/open.html.erb
<h5>
  <i class="fa fa-file-alt" aria-hidden="true"></i> <%= link_to @exam.name, @exam %> 
</h5>
<br/>

<%= form_tag(exam_exam_eval_path, method: "post", local: true, class: '') do %>
    <ol>
    <% @exam.questions.order("position").each do |question| %>
        <li class="mb-5">
            <h5><%= question.content %></h5>
            <div>
                <% question.options.order("position").each do |option| %>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="options_question[<%= option.id %>]" id="option_<%= option.id %>" value="true">
                        <label class="form-check-label" for="option_<%= option.id %>">
                            <%= option.content %>
                        </label>
                    </div>
                <% end %>
            </div>
        </li>
    <% end %>
    </ol>
    <%= submit_tag "Enviar Resultados", class: 'btn btn-primary float-right' %>
<% end %>

app/views/exams/result.html.erb
<br/>
<h3 class="shadow p-3"><i class="fa fa-file-alt" aria-hidden="true"></i> Resultados <%= @exam.name %></h3>
<br/>

<% @exam.questions.order("position").each do |question| %>
    <div class="mb-3 p-3 shadow">
        <h5><%= question.position %>.- <%= question.content %></h5>
        <div>
            <% question.options.order("position").each do |option| %>
                <div class="form-check border my-2 py-2 <%= option.is_correct ? 'alert alert-success' : '' %>">
                    <input class="form-check-input ml-0" type="radio" name="options_question[<%= option.id %>]" id="option_<%= option.id %>" <%= current_user.answer_checked(@exam.id, option.id) ? "checked" : "" %> value="true">
                    <label class="form-check-label ml-4" for="option_<%= option.id %>">
                        <%= option.content %>
                    </label>
                </div>
            <% end %>
        </div>
    </div>
<% end %>

<%= link_to 'Volver', root_path, :class => "float-left btn btn-secondary" %>

app/views/exams/show.html.erb
<p id="notice"><%= notice %></p>

<h3 class="shadow p-3">
  <i class="fa fa-file-alt" aria-hidden="true"></i> <%= link_to @exam.name, @exam %> 
  <%= link_to '<i class="fa fa-edit float-right text-warning"></i>'.html_safe, edit_exam_path(@exam) %>
</h3>

<div class="p-3 shadow">
  <%= link_to 'Nueva Pregunta', new_exam_question_path(@exam), :class => "float-right btn btn-primary mb-2" %>
  <h5>Preguntas</h5>

  <table class="table table-bordered">
    <thead class="bg-dark text-white">
      <tr>
        <th>Posición</th>
        <th>Pregunta</th>
        <th>Opciones</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= render @exam.questions %>
    </tbody>
  </table>
</div>

app/views/home/index.html.erb
<br/>
<h3 class="shadow p-3">Examenes disponibles</h3>
<br/>
<%= render @exams %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/options/_form.html.erb
<%= form_with(model: [@question.exam, @question, option], local: true) do |form| %>
  <% if option.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(option.errors.count, "error") %> prohibited this option from being saved:</h2>

      <ul>
        <% option.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label "Posición" %>
    <%= form.number_field :position, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label "Opción" %>
    <%= form.text_field :content, :class => "form-control" %>
  </div>

  <div class="form-check">
    <%= form.check_box :is_correct, :class => "form-check-input" %>
    <%= form.label "Es Correcta?", :class => "form-check-label" %>
  </div>

  <div class="form-group text-right mt-4">
    <%= link_to 'Volver', exam_question_options_path(@question.exam, @question), :class => "float-left btn btn-secondary" %>
    <%= form.submit 'Guardar', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/options/edit.html.erb
<p id="notice"><%= notice %></p>

<h5><i class="fa fa-file-alt" aria-hidden="true"></i> <%= link_to @question.exam.name, @question.exam %></h5>
<h5><b>Pregunta:</b> <%= @question.content %></h5>
<br/>

<div class="p-3 shadow">
    <h3>Editar Opción</h3>
    <%= render 'form', option: @option %>
</div>

app/views/options/index.html.erb
<p id="notice"><%= notice %></p>

<h3 class="p-3 shadow"><i class="fa fa-file-alt" aria-hidden="true"></i> <%= link_to @question.exam.name, @question.exam %></h3>

<h3 class="p-3 shadow"><%= @question.content %></h3>
<br/>

<div class="p-3 shadow">
  <%= link_to 'Nueva Opción', new_exam_question_option_path(@question.exam, @question), :class => "float-right btn btn-primary mb-2" %>
  <h3>Opciones</h3>

  <table class="table table-bordered">
    <thead class="bg-dark text-white">
      <tr>
        <th>Posición</th>
        <th>Opción</th>
        <th>Es Correcta?</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @options.each do |option| %>
        <tr>
          <td><%= option.position %></td>
          <td><%= option.content %></td>
          <td><%= option.is_correct ? "Si" : "No" %></td>
          <td class="text-right">
            <%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_exam_question_option_path(@question.exam, @question, option) %> 
            <%= link_to '<i class="fa fa-trash"></i>'.html_safe, exam_question_option_path(@question.exam, @question, option), :class=>"text-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/options/new.html.erb
<p id="notice"><%= notice %></p>

<h5><i class="fa fa-file-alt" aria-hidden="true"></i> <%= link_to @question.exam.name, @question.exam %></h5>
<h5><b>Pregunta:</b> <%= @question.content %></h5>
<br/>

<div class="p-3 shadow">
    <h3>Nueva Opción</h3>
    <%= render 'form', option: @option %>
</div>

app/views/options/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @option.content %>
</p>

<p>
  <strong>Position:</strong>
  <%= @option.position %>
</p>

<p>
  <strong>Is correct:</strong>
  <%= @option.is_correct %>
</p>

<p>
  <strong>Question:</strong>
  <%= @option.question_id %>
</p>

<%= link_to 'Edit', edit_option_path(@option) %> |
<%= link_to 'Back', options_path %>

app/views/questions/_form.html.erb
<%= form_with(model: [@exam, question], local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
        <% question.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label "Posición" %>
    <%= form.number_field :position, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label "Contenido" %>
    <%= form.text_field :content, :class => "form-control" %>
  </div>

  <div class="form-group text-right mt-4">
    <%= link_to 'Volver', exam_path(@exam), :class => "float-left btn btn-secondary" %>
    <%= form.submit 'Guardar', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/questions/_question.html.erb
<tr>
    <td><%= question.position %></td>
    <td><%= question.content %></td>
    <td><%= link_to "Posibles Respuestas: #{question.options.count}", exam_question_options_path(@exam, question) %></td>
    <td class="text-right">
        <%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_exam_question_path(@exam, question) %>
        <%= link_to '<i class="fa fa-trash"></i>'.html_safe, exam_question_path(@exam, question), :class=>"text-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
    </td>
</tr>

app/views/questions/edit.html.erb
<p id="notice"><%= notice %></p>

<h3 class="shadow p-3">
  <i class="fa fa-file-alt" aria-hidden="true"></i> <%= link_to @exam.name, @exam %> 
  <%= link_to '<i class="float-right fa fa-edit text-warning"></i>'.html_safe, edit_exam_path(@exam) %>
</h3>
<br/>

<div class="p-3 shadow">
  <h5>Editar Pregunta</h5>
  <%= render 'form', question: @question %>
</div>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questions</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Position</th>
      <th>Exam</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.content %></td>
        <td><%= question.position %></td>
        <td><%= question.exam_id %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<p id="notice"><%= notice %></p>

<h3 class="shadow p-3">
  <i class="fa fa-file-alt" aria-hidden="true"></i> <%= link_to @exam.name, @exam %> 
  <%= link_to '<i class="float-right fa fa-edit text-warning"></i>'.html_safe, edit_exam_path(@exam) %>
</h3>
<br/>

<div class="p-3 shadow">
  <h5>Nueva Pregunta</h5>
  <%= render 'form', question: @question %>
</div>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @question.content %>
</p>

<p>
  <strong>Position:</strong>
  <%= @question.position %>
</p>

<p>
  <strong>Exam:</strong>
  <%= @question.exam_id %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>

app/views/shared/_navbar.html.erb
<div class="w-100 bg-dark">
    <nav class="navbar navbar-expand-lg container">
        <div class="d-flex flex-grow-1">
            <span class="w-100 d-lg-none d-block"><!-- hidden spacer to center brand on mobile --></span>
            <b><%= link_to "Quiz", root_path, :class => "navbar-brand text-white"%></b>
            <div class="w-100 text-right">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#myNavbar7">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </div>
        <div class="collapse navbar-collapse flex-grow-1 text-right" id="myNavbar7">
            <ul class="navbar-nav ml-auto flex-nowrap">
                <% if user_signed_in? %>
                <li class="nav-item">
                    <%= link_to "Exams Manager", exams_path, :class => "nav-link text-white"%>
                </li>
                <% end %>
                <li class="nav-item">
                    <% if user_signed_in? %>
                        <%= link_to 'Salir', destroy_user_session_path, method: :delete, :class => "nav-link text-white" %>
                    <% else %>
                        <%= link_to 'Acceder', new_user_session_path, :class => "nav-link text-white" %>
                    <% end %>
                </li>
            </ul>
        </div>
    </nav>
</div>